name: html_template
description: A server-side HTML template engine based on String interpolation.
version: 0.1.1
homepage: https://github.com/xvrh/html_template

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: '>=0.40.0 <0.42.0'
  build: ^1.5.0
  dart_style: ^1.3.9
  html: ^0.14.0
  meta: ^1.0.0
  source_gen: ^0.9.8

dev_dependencies:
  build_runner:
  build_test:
  build_web_compilers:
  pedantic: ^1.9.0
  test:
  path:
  yaml:
