name: html_template
description: A server-side HTML template engine based on String interpolation.
version: 0.3.0
homepage: https://github.com/xvrh/html_template

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  analyzer: '>=4.0.0 <=6.0.0'
  build: ^2.0.0
  dart_style: ^2.0.0
  html: ^0.15.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner:
  build_test:
  lints:
  path:
  shelf:
  test:
  yaml:
